// English. Every key mirrors de.mjs (the source).
export default {
  lang: "en",
  dir: "ltr",
  name: "English",
  meta: {
    title: "Diwan — your assistant for German correspondence",
    description:
      "Diwan understands official German post, writes the reply in correct German and sends it — by e-mail or as a paper letter. With tasks, deadlines, an archive and invoices for businesses. Interface in five languages.",
    ogTitle: "Diwan — German correspondence without the hurdles",
    ogDescription: "Understand, write, send — e-mail and paper post in one app. First month free, no contract.",
  },
  nav: {
    problem: "The problem",
    features: "Features",
    video: "Video",
    security: "Security",
    price: "Price",
    open: "Open the app",
    language: "Language",
  },
  hero: {
    h1: "German correspondence should <span class=\"gold\">hold nobody back</span>",
    sub: "Diwan understands official post, writes the reply in correct German and sends it — by e-mail or as a real paper letter. For everyone who receives post in Germany: explained in your language if you want it. You review and approve.",
    ctaStart: "Start for free",
    ctaVideo: "Watch the video",
    chip: "🎁 The first month is free — then from €3.99/month, cancel any time",
  },
  problem: {
    kicker: "The problem",
    h2: "Official post costs <span class=\"gold\">time and nerves</span>",
    lead: "Letters and e-mails from authorities, insurers, landlords and customers demand an answer in a particular form, by a particular day. Those who do not speak German natively often cannot read them. Those who do rarely have the time to answer them properly.",
    cards: [
      { icon: "⏰", title: "Deadlines", text: "\"Within 14 days\" — counting from when? Leave the letter lying around and the next one is a reminder with a fee." },
      { icon: "✍️", title: "The right form", text: "Reading official German is hard. Writing it correctly — salutation, reference number, tone — is work, even for native speakers." },
      { icon: "🖨️", title: "Paper", text: "Print, envelope, walk to the post office, registered mail, keep the receipt — for every single reply." },
    ],
  },
  who: {
    kicker: "Who it is for",
    h2: "For <span class=\"gold\">everyone</span> who receives post in Germany",
    lead: "The biggest gain is for people who are new here. But even German speakers write faster, more safely and in the right form with Diwan — at home and at work.",
    cards: [
      { icon: "🧑‍💼", title: "Individuals", text: "understand and answer their post with confidence: the authority, the landlord, the insurer, the health fund. Explained in your language, answered in German, sent with a click." },
      { icon: "🏪", title: "Small businesses", text: "Correspondence with authorities, customers and suppliers from one mailbox — with the company details a business letter must carry, and invoices that survive an audit." },
    ],
    langsLabel: "The interface speaks five languages:",
  },
  video: {
    kicker: "Diwan in two and a half minutes",
    h2: "See Diwan <span class=\"gold\">in action</span>",
    lead: "Real recordings from the application: understand, write, send, deadlines, archive, five languages and invoices — narrated in German.",
    note: "Video language: German.",
  },
  features: {
    kicker: "Features in detail",
    h2: "From the letterbox to the reply — <span class=\"gold\">one tool</span>",
    lead: "Every recording below comes straight from the running application.",
    items: [
      {
        num: "01 — Understand",
        h3: "One tap. <span class=\"gold\">Understood.</span>",
        text: "Diwan connects to the e-mail mailboxes you already have. When an official message arrives, one tap is enough — Diwan explains it in your language:",
        bullets: ["What is demanded — as a clear list", "Which documents are needed", "By when? The deadline comes first"],
        video: "explain.mp4",
      },
      {
        num: "02 — Write",
        h3: "Notes in, <span class=\"gold\">correct German</span> out",
        text: "You write your reply as a simple note — in German, Arabic, English, Russian, Ukrainian or any other language. Diwan turns it into a correct German letter in the right form. Your own text can be restored with one click at any time. Nothing is sent automatically — you decide.",
        video: "write.mp4",
      },
      {
        num: "03 — Ask instead of guess",
        h3: "The AI <span class=\"gold\">does not guess</span> — it asks",
        text: "If information is missing, Diwan asks targeted questions first — \"Do you already have the proof of residence?\" — and only writes after your answer. The letters are realistic rather than speculative, and the confirmed facts are stated with authority.",
        video: "clarify.mp4",
      },
      {
        num: "04 — Paper post",
        h3: "Real letters, <span class=\"gold\">fully digital</span>",
        text: "Many offices still write on paper — Diwan closes exactly that gap. Photograph the letter; Diwan reads and explains it and recognises deadlines and required documents. The reply goes out as a real letter straight from the app — no printer, no trip to the post office.",
        video: "paper.mp4",
      },
      {
        num: "05 — Print, post & proof",
        h3: "Printed, enveloped, <span class=\"gold\">delivered</span>",
        text: "When you send, Diwan takes care of everything: printing, enveloping, delivery — by registered mail if you wish. Attachments are printed and sent in the same letter. The proof of dispatch stays in the app, available at any time.",
        video: "print.mp4",
      },
      {
        num: "06 — Tasks & deadlines",
        h3: "Deadlines become <span class=\"gold\">tasks</span> — automatically",
        text: "Letters and e-mails turn into tasks, appointments and reminders — with a deadline per required document and a reminder before every appointment. Nothing gets lost by accident any more.",
        video: "tasks.mp4",
      },
    ],
  },
  more: {
    kicker: "And beyond that",
    h2: "A <span class=\"gold\">complete</span> mailbox cockpit",
    businessBadge: "Business accounts only",
    cards: [
      { icon: "🌍", title: "Five languages", text: "The interface in German, Arabic, English, Russian or Ukrainian — the letter stays correct German. Switch at any time without signing in again." },
      { icon: "🗂️", title: "Secure archive", text: "E-mails, attachments, letters and documents stay stored and are at hand for any later question. Diwan never deletes your correspondence on its own." },
      { icon: "🔍", title: "Deep search", text: "Finds the one line in years of post — across e-mails, attachments, letters and drafts, with a literal quote." },
      { icon: "🧾", title: "Invoices", business: true, text: "Invoices to your customers straight from Diwan — as a PDF with an embedded e-invoice (ZUGFeRD / EN 16931), with your tax identifiers, numbered consecutively and unchangeable. You always choose the VAT rate." },
      { icon: "🏢", title: "Company details, automatically", business: true, text: "Enter the commercial register, the court and the VAT ID once — Diwan places them in every business letter, as German law requires (§ 37a HGB, § 14 UStG)." },
      { icon: "📥", title: "Several mailboxes", text: "All accounts in one place — with a selectable sender per e-mail. Gmail via Google sign-in, everything else via IMAP." },
      { icon: "📅", title: "Appointment booking", text: "Your own booking page: customers or clients pick a free slot, Diwan confirms and reminds." },
      { icon: "🤖", title: "Automatic replies", text: "Global or per sender — AI-assisted, always by your rules." },
      { icon: "🕐", title: "Scheduled sending", text: "Send e-mails at the time you choose instead of right away. Unwanted senders go to the bin automatically." },
    ],
  },
  security: {
    kicker: "Security & control",
    h2: "Your data. <span class=\"gold\">Your control.</span>",
    cards: [
      { icon: "🇪🇺", title: "Stored in Germany", text: "Database, documents, background service and AI processing run in Frankfurt am Main — in the EU by default. Which provider processes what is stated openly in the privacy policy." },
      { icon: "🔒", title: "No training on your data", text: "Your post is not used to train AI models. That is recorded contractually with every AI provider we use and can be read in the data processing agreement." },
      { icon: "👤", title: "The human decides", text: "Diwan never sends automatically. Every letter is reviewed by you and explicitly approved. AI suggestions remain suggestions." },
      { icon: "🔌", title: "AI can be switched off", text: "The AI functions can be switched off in the settings at any time. Then no content leaves your mailbox — and the rest of Diwan stays fully usable." },
    ],
    links: "In full (in German): <a href=\"/datenschutz-app.html\">privacy policy of the application</a> · <a href=\"/avv.html\">data processing agreement</a> · <a href=\"/ki-hinweis.html\">AI notice</a>",
  },
  pricing: {
    kicker: "The price",
    h2: "Two plans. <span class=\"gold\">No contract.</span>",
    lead: "The first month is free — with every feature. After that monthly, cancel any time, no minimum term.",
    plans: [
      { name: "Individuals", price: "€3.99", per: "per month", features: ["Understand, write, send", "Tasks, deadlines, archive", "Up to 2 mailboxes", "Interface in five languages"] },
      { name: "Business", price: "€9.99", per: "per month", highlight: true, features: ["Everything in Individuals", "Invoices with e-invoice", "Company details in every letter", "Deep search included", "Up to 6 mailboxes", "Data processing agreement (AVV)"] },
    ],
    note: "Paper letters are charged per letter by pages and delivery type — the price is shown before every order. All prices include VAT.",
    cta: "Start for free",
  },
  company: {
    kicker: "The company",
    h2: "Developed by <span class=\"gold\">Swift Assets UG</span>",
    text: "Diwan is a product of Swift Assets UG (haftungsbeschränkt), based in Solingen, North Rhine-Westphalia. Built from our own experience — for everyone who arrives, works and founds in Germany.",
    contact: "Contact:",
  },
  footer: {
    impressum: "Legal notice (Impressum)",
    datenschutz: "Privacy",
    agb: "Terms (AGB)",
    avv: "Data processing (AVV)",
    ki: "AI notice & liability",
    contact: "Contact",
    legalNote: "Legal texts are in German — the German version is binding.",
  },
};
